### PR TITLE
Revert "Revert "add fee proposer recipient to beacon chain""

### LINKED ISSUE #38: Teku Gnosis
Tracked and detailed in https://github.com/dappnode/DAppNodePackage-teku/issues/34

### PR DESCRIPTION
**Pull request by alexpeterson91**
Reverts dappnode/DAppNodePackage-teku-gnosis#41

Fixes #38

### CODE REVIEW

**Comment by tropicar** [comment]
I have this error, testing this branch 
```
2022-12-01 16:00:36.224 ERROR - Failed to update eth1 chain head
org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 403; {"jsonrpc":"2.0","error":{"code":-32600,"message":"Authentication error"},"id":null}
at org.web3j.protocol.http.HttpService.performIO(HttpService.java:178) ~[core-4.9.4.jar:?]
at org.web3j.protocol.Service.send(Service.java:48) ~[core-4.9.4.jar:?]
at org.web3j.protocol.Service.lambda$sendAsync$0(Service.java:60) ~[core-4.9.4.jar:?]
at org.web3j.utils.Async.lambda$run$1(Async.java:38) ~[core-4.9.4.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
2022-12-01 16:00:38.227 ERROR - Failed to update eth1 chain head
```

**Comment by tropicar** [comment]
> I have this error, testing this branch
> 
> ```
> 2022-12-01 16:00:36.224 ERROR - Failed to update eth1 chain head
> org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 403; {"jsonrpc":"2.0","error":{"code":-32600,"message":"Authentication error"},"id":null}
> at org.web3j.protocol.http.HttpService.performIO(HttpService.java:178) ~[core-4.9.4.jar:?]
> at org.web3j.protocol.Service.send(Service.java:48) ~[core-4.9.4.jar:?]
> at org.web3j.protocol.Service.lambda$sendAsync$0(Service.java:60) ~[core-4.9.4.jar:?]
> at org.web3j.utils.Async.lambda$run$1(Async.java:38) ~[core-4.9.4.jar:?]
> at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
> at java.lang.Thread.run(Unknown Source) ~[?:?]
> 2022-12-01 16:00:38.227 ERROR - Failed to update eth1 chain head
> ```

The error appears because is not using the current version of the main branch.

**Comment by pablomendezroyo** [comment]
This PR breaks.

I will not work with the current dappmanager, setting an empty fee recipient, which is whats going to happen will result into a restarting loop

**Comment by alexpeterson91** [comment]
> This PR breaks.
> 
> I will not work with the current dappmanager, setting an empty fee recipient, which is whats going to happen will result into a restarting loop

will it work with the PR i have open for the dappmanager to handle this?

**Comment by alexpeterson91** [comment]
> > I have this error, testing this branch
> > ```
> > 2022-12-01 16:00:36.224 ERROR - Failed to update eth1 chain head
> > org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: 403; {"jsonrpc":"2.0","error":{"code":-32600,"message":"Authentication error"},"id":null}
> > at org.web3j.protocol.http.HttpService.performIO(HttpService.java:178) ~[core-4.9.4.jar:?]
> > at org.web3j.protocol.Service.send(Service.java:48) ~[core-4.9.4.jar:?]
> > at org.web3j.protocol.Service.lambda$sendAsync$0(Service.java:60) ~[core-4.9.4.jar:?]
> > at org.web3j.utils.Async.lambda$run$1(Async.java:38) ~[core-4.9.4.jar:?]
> > at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
> > at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
> > at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
> > at java.lang.Thread.run(Unknown Source) ~[?:?]
> > 2022-12-01 16:00:38.227 ERROR - Failed to update eth1 chain head
> > ```
> 
> The error appears because is not using the current version of the main branch.

yeah this was written 2 core versions ago, and was a revert of a revert since as Pablo said the change would also need a dappmanager change which hasnt been merged but is a PR, i just havent gotten to test it yet, since i got on testing too late and instead found a bunch of other issues that remain unfixed in teku i need to document them here, i just had sent some of the issues i found to Pablo over discord DM since i didnt have time when i discovered it to fix it and also some of it had multiple ways to fix it and i wanted feedback, im just way behind on GH right now since I havent fully gotten back from my holiday yet. just been dealing with necessary stuff like the website change etc. gotta get to all my messages on discord too i know i have some from both you guys

**Pull request merged**
